coverage:
    precision: 2
    round: down
    range: "60...100"

    status:
        project:
            default: on
        patch:
            default: off
        changes:
            default: off
