language: python
cache: pip
install:
    - . scripts/ci/setup.sh
jobs:
  include:
    - stage: precheck
      script: . scripts/ci/precheck.sh
      python: 3.6
    - stage: test
      script: python test/test_alias.py
      python: 3.6
    - stage: test
      script: python test/test_alias.py
      python: 2.7
