language: python
cache: pip
jobs:
  include:
    - stage: precheck
      script: . scripts/ci/precheck.sh
      python: 3.6
    - stage: precheck
      script: . scripts/ci/precheck.sh
      python: 2.7
    - stage: automation
      before_script: . scripts/ci/test_setup.sh
      script: . scripts/ci/test_automation.sh
      python: 3.6
    - stage: automation
      before_script: . scripts/ci/test_setup.sh
      script: . scripts/ci/test_automation.sh
      python: 2.7
